services:
  postgres:
    image: docker.io/postgres:17
    container_name: numby-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: numby
    volumes:
      - numby-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  valkey:
    image: docker.io/valkey/valkey:8
    container_name: numby-valkey
    volumes:
      - numby-valkey:/data
    ports:
      - "6379:6379"

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    container_name: numby-jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "6831:6831/udp" # Jaeger thrift compact protocol
      - "6832:6832/udp" # Jaeger thrift binary protocol
      - "5778:5778" # Jaeger admin port
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "14250:14250" # Model/collector gRPC
      - "14268:14268" # Jaeger collector HTTP
      - "9411:9411" # Zipkin compatible endpoint

volumes:
  numby-postgres:
  numby-valkey:
