services:
  postgres:
    image: docker.io/postgres:17
    container_name: numby-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: numby
    volumes:
      - numby-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  valkey:
    image: docker.io/valkey/valkey:8
    container_name: numby-valkey
    volumes:
      - numby-valkey:/data
    ports:
      - 6379:6379

  jaeger:
    image: docker.io/jaegertracing/jaeger:latest
    container_name: numby-jaeger
    command:
      - --set=receivers.otlp.protocols.grpc.endpoint="0.0.0.0:4317"
      - --set=receivers.otlp.protocols.http.endpoint="0.0.0.0:4318"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: numby-selenium
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=30
    ports:
      - 4444:4444
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mathesar:
    image: docker.io/mathesar/mathesar:latest
    container_name: numby-mathesar
    environment:
      SECRET_KEY: ZxB2HafGwOeOGoRkmcANDaPY0rO3ytJzde3jwkkACfsKukcz7m
      POSTGRES_USER: mathesar
      POSTGRES_PASSWORD: mathesar
      POSTGRES_DB: mathesar_django
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5430
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    ports:
      - 8000:8000
    volumes:
      - mathesar-static:/code/static
      - mathesar-media:/code/media
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mathesar-db:
    image: docker.io/pgautoupgrade/pgautoupgrade:17-bookworm
    container_name: numby-mathesar-postgres
    environment:
      POSTGRES_USER: mathesar
      POSTGRES_PASSWORD: mathesar
      POSTGRES_DB: mathesar_django
    volumes:
      - mathesar-postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432

volumes:
  numby-postgres:
  numby-valkey:
  mathesar-static:
  mathesar-media:
  mathesar-postgres:
