[tasks.start]
description = "Start numby"
run = "cargo watch -x run"

[tasks."db:setup"]
description = "Setup database and run migrations"
run = "sqlx database setup --source db/migrations"

[tasks."db:drop"]
description = "Drop database"
run = "sqlx database drop"

[tasks."db:codegen"]
description = "Codegen db queries"
run = "clorinde schema db/migrations/*.up.sql"

[tasks."db:migrate:run"]
description = "Run db migrations"
run = "sqlx migrate run --source db/migrations"

[tasks."db:migrate:add"]
description = "Add a db migration"
run = "sqlx migrate add --source db/migrations -r"

[tasks."db:migrate:fixture"]
description = "Add a fixture for tests"
run = "sqlx migrate add --source db/fixtures"

[env]
_.source = "./env.sh"

DATABASE_URL = "postgres://postgres:numby@localhost/numby"
VALKEY_URL = "valkey://localhost:6379"

OTEL_SERVICE_NAME = "numby"
OTEL_SERVICE_VERSION = "1.0"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "http://127.0.0.1:4317"
OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = "grpc"
OTEL_TRACES_SAMPLER = "always_on"

[tools]
bun = "latest"
"cargo:cargo-watch" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:clorinde" = "latest"
