[tasks."app:start"]
alias = ["start"]
description = "Start podman services and numby"
run = ["podman compose up -d", "cargo watch -i tests/ -x run"]

[tasks."app:setup"]
description = "Initial setup for app"
run = ["podman compose up -d", "sqlx database setup --source db/migrations"]

[tasks."test:unit"]
description = "Run unit tests"
run = "cargo test --bin numby"

[tasks."test:integration"]
description = "Run integration tests"
run = "cargo test --features test.integration"

[tasks."test:e2e"]
description = "Run end-to-end tests"
run = "cargo test --features test.e2e"

[tasks."db:codegen"]
description = "Codegen db queries"
run = "clorinde schema db/migrations/*.up.sql"

[tasks."db:migrate:run"]
description = "Run db migrations"
run = "sqlx migrate run --source db/migrations"

[tasks."db:migrate:add"]
description = "Add a db migration"
run = "sqlx migrate add --source db/migrations -r"

[tasks."db:fixture"]
description = "Add a testing db fixture"
run = "sqlx migrate add --source db/fixtures"

[env]
_.source = ".envrc"

DATABASE_URL = "postgres://postgres:numby@localhost/numby"
VALKEY_URL = "valkey://localhost:6379"

OTEL_SERVICE_NAME = "numby"
OTEL_SERVICE_VERSION = "1.0"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "http://127.0.0.1:4317"
OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = "grpc"
OTEL_TRACES_SAMPLER = "always_on"

[tools]
rust = { version = "nightly", components = "rust-analyzer,rustfmt,clippy" }
bun = "latest"
"cargo:cargo-watch" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:clorinde" = "latest"
